use getops in tmux setup

diff --git a/script/tmux_setup b/script/tmux_setup
--- a/script/tmux_setup
+++ b/script/tmux_setup
@@ -1,27 +1,37 @@
 #! /bin/bash -e
 
-server_started="$1"
-name="$2"
-start_server=false
 tmux_window_names=("git" "run" "edit" "test"  "console" "ssh")
 tmux_window_names_length=${#tmux_window_names[@]}
+start_server=false
+name="$(basename $PWD)"
 
+while getopts ":on:" opt; do
+  case $opt in
+    o)
+      start_server=true
+      ;;
+    n)
+      name="$OPTARG"
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
 
-if [ "$1" = "on" ]; then
-  start_server=true
-fi
-
-if [ -z "$2" ]; then
-  name="$(basename $PWD)"
-fi
+echo "start_server = $start_server"
+echo "name = $name"
 
 echo -e "\033];$name\007" # set iTerm tab title
 
 tmux new-session -d -s "$name"
 tmux rename-window ${tmux_window_names[0]}
 
-for (( i=1; i<tmux_window_names_length; i++ ))
-do
+for (( i=1; i<tmux_window_names_length; i++ )); do
   tmux new-window -n "${tmux_window_names[$i]}"
 done
 
